### Health Check

GET http://localhost:3000/health HTTP/1.1

### tasks

GET http://localhost:3000/v1/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkhiNHQ4TjVmRlJBYmZacmRNdU5EMSJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZ2dyNzdyaXpiNzRuZmxiLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwODA1NTY3NjQ1ODY1MzA5NTI2NCIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtcWdncjc3cml6Yjc0bmZsYi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzU2MTQ5NDI5LCJleHAiOjE3NTYxNTY2MjksInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiZ0VzcXJ4RW9pM0VWSllxTGFnMUNWZFd0Q0pCSDhNREEifQ.Rtd-X1E0X7ADH1NhO8bauBsW4oXM1YUYxXfbSduvCRdJmJw1eJJyTAZiy7SKj2x0n1Ea87jgTYGJLIj9ZNfiZs7E131xcABPynFpIXCKNUoEVx5FRpprfxeYwD1im7zZ1tNVreyl-GXdw0W3oFDTg81vN1ROtS9tR_L7bjSjhgaehB-RJgOnEHP0O6V97EPjQ1LIXy5NNzBYU5k3c--xmyfeA1kOOkEmzBM1-9ShL7eL629mUSdwXKPWqJzpcV0Xxw1mnc4Jqn6M-hh9qY2thfYZJvRHZlGKdwLsO3HoMNJCS5dmHNYK4xaOBZ3P9MtmwK9OMtwn0mygPBvmOQeR_Q

###GET task by ID

GET http://localhost:3000/v1/tasks/1 HTTP/1.1
Authorization: Bearer <token>

###GET projects

GET http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer <token>

###GET project by ID

GET http://localhost:3000/v1/projects/1 HTTP/1.1
Authorization: Bearer <token>

###GET project's tasks

GET http://localhost:3000/v1/projects/1/tasks HTTP/1.1
Authorization: Bearer <token>